-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaYQcBekXsIkKU5Cw
J0SZeVVN1WUXqJvseC65JpoVyiCgCgYIKoZIzj0DAQehRANCAATIrITwtMNRfhY2
z5A+XPBoVC6p6V3Ct3LYonJlMRgAkgWLJuzGfkM+FvN+acqZ5epGtLv0knlNq6e7
TMknfKAs
-----END PRIVATE KEY-----